const employees = [
  {
    "id": 1,
    "firstName": "Priya",
    "email": "test1@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 3,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Write Team Report #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-13",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-18",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Dark Mode Design #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-23",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix Login Bug #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-05",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Test API Endpoints #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-30",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 2,
    "firstName": "Anirudh",
    "email": "test2@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Improve Animations #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-06",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Prepare Release Notes #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-10",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix NavBar #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-28",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Design Login Page #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-01",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 3,
    "firstName": "Rajat",
    "email": "test3@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 3,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Build Dashboard Page #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-24",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "API Response Delay Fix #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-29",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Design Icons #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-11",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Prepare Release Notes #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-18",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 4,
    "firstName": "Pratham",
    "email": "test4@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 0,
      "failed": 2
    },
    "tasks": [
      {
        "title": "User Feedback Testing #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-26",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Optimize Database #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-07",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-27",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "User Feedback Testing #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-05",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 5,
    "firstName": "Alok",
    "email": "test5@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 0,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "System Load Testing #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-10",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Test Mobile Layout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-26",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 6,
    "firstName": "Ritika",
    "email": "test6@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 3,
      "completed": 3,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix NavBar #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-05",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "User Feedback Testing #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-02",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-06",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-17",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Update README File #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-22",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-15",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "System Load Testing #7",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-24",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 7,
    "firstName": "Sneha",
    "email": "test7@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 3,
      "completed": 0,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Database Migration #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-12",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Design Login Page #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-04",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Database Migration #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-15",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Admin Panel #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-05",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Unit Tests #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-18",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 8,
    "firstName": "Sameer",
    "email": "test8@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 0,
      "completed": 2,
      "failed": 2
    },
    "tasks": [
      {
        "title": "Fix API Timeout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-05",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Optimize Database #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-04",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Design Login Page #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-16",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Update README File #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-19",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 9,
    "firstName": "Riya",
    "email": "test9@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 3,
      "completed": 1,
      "failed": 2
    },
    "tasks": [
      {
        "title": "Prepare Release Notes #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-09",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Improve Animations #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-11",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Deploy to Production #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-03",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "API Response Delay Fix #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-11",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Create Contact Page #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-23",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Improve Animations #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-31",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 10,
    "firstName": "Sagar",
    "email": "test10@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Test Mobile Layout",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-19",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 11,
    "firstName": "Pooja",
    "email": "test11@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix NavBar #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-06",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-20",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Design Icons #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-31",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 12,
    "firstName": "Siddharth",
    "email": "test12@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix NavBar",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-09",
        "category": "Documentation",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 13,
    "firstName": "Deepak",
    "email": "test13@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 4,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Test Mobile Layout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-28",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-23",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Prepare Release Notes #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-02",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Design Login Page #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-23",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 14,
    "firstName": "Aman",
    "email": "test14@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Deploy to Production",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-09",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 15,
    "firstName": "Ishita",
    "email": "test15@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 0,
      "completed": 0,
      "failed": 3
    },
    "tasks": [
      {
        "title": "Fix API Timeout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-08",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Test Mobile Layout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-02",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Redesign Icons #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-20",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Design Login Page #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-14",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Build Dashboard Page #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-21",
        "category": "Documentation",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 16,
    "firstName": "Kirti",
    "email": "test16@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 2,
      "completed": 2,
      "failed": 2
    },
    "tasks": [
      {
        "title": "Design Icons #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-12",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Mobile Layout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-22",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-01",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Contact Page #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-02",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "System Load Testing #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-22",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Test API Endpoints #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-06",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 17,
    "firstName": "Krish",
    "email": "test17@e.com",
    "password": "123",
    "taskCount": {
      "active": 3,
      "newTask": 2,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Test Mobile Layout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-01",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Implement Loader #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-19",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix Login Bug #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-14",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Contact Page #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-17",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Build Dashboard Page #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-15",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "User Feedback Testing #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-09",
        "category": "Documentation",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 18,
    "firstName": "Ritesh",
    "email": "test18@e.com",
    "password": "123",
    "taskCount": {
      "active": 3,
      "newTask": 1,
      "completed": 1,
      "failed": 2
    },
    "tasks": [
      {
        "title": "Create Admin Panel #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-07",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Contact Page #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-21",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "System Load Testing #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-16",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Implement Loader #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-05",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Design Login Page #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-13",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Database Migration #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-01",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix API Timeout #7",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-11",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 19,
    "firstName": "Simran",
    "email": "test19@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Implement Loader",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-10",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 20,
    "firstName": "Aditya",
    "email": "test20@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix Button Style",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-11",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 21,
    "firstName": "Mira",
    "email": "test21@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 2,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Prepare Release Notes #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-25",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Test Mobile Layout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-16",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Implement Loader #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-27",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-22",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Log Cleanup #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-08",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 22,
    "firstName": "Mayank",
    "email": "test22@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 0,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Write Deployment Guide #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-28",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Write Team Report #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-08",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix API Timeout #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-09",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Update README File #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-07",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 23,
    "firstName": "Aditi",
    "email": "test23@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 3,
      "completed": 2,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Test Mobile Layout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-21",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Unit Tests #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-08",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-28",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Create Admin Panel #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-02",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Design Icons #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-01",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-20",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Test Mobile Layout #7",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-08",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 24,
    "firstName": "Tanvi",
    "email": "test24@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 2,
      "completed": 1,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Write Team Report #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-15",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Write Unit Tests #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-13",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix API Timeout #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-27",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Prepare Release Notes #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-24",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Test API Endpoints #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-23",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "User Feedback Testing #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-14",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 25,
    "firstName": "Nandini",
    "email": "test25@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 0,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Write Team Report",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-14",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 26,
    "firstName": "Nisha",
    "email": "test26@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 1,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Fix Login Bug #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-25",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-10",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "System Load Testing #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-01",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 27,
    "firstName": "Kavya",
    "email": "test27@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Build Dashboard Page #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-23",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Admin Panel #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-03",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 28,
    "firstName": "Ankit",
    "email": "test28@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix NavBar",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-19",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 29,
    "firstName": "Harsh",
    "email": "test29@e.com",
    "password": "123",
    "taskCount": {
      "active": 4,
      "newTask": 0,
      "completed": 3,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Write Team Report #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-03",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Update README File #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-17",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-07",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "User Feedback Testing #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-13",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix Mobile Layout #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-27",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix Mobile Layout #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-27",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Contact Page #7",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-07",
        "category": "Documentation",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 30,
    "firstName": "Suhana",
    "email": "test30@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 2,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix NavBar #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-20",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Implement Loader #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-28",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix NavBar #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-21",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix API Timeout #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-01",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 31,
    "firstName": "Sonali",
    "email": "test31@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Optimize Database #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-13",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Redesign Icons #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-09",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 32,
    "firstName": "Shreya",
    "email": "test32@e.com",
    "password": "123",
    "taskCount": {
      "active": 3,
      "newTask": 1,
      "completed": 0,
      "failed": 2
    },
    "tasks": [
      {
        "title": "Create Contact Page #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-10",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Unit Tests #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-03-17",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Test Mobile Layout #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-24",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Design Icons #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-23",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-08",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Design Icons #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-26",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 33,
    "firstName": "Meera",
    "email": "test33@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 0,
      "completed": 5,
      "failed": 0
    },
    "tasks": [
      {
        "title": "API Response Delay Fix #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-15",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Implement Loader #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-16",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-17",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Redesign Icons #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-19",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-23",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 34,
    "firstName": "Anaya",
    "email": "test34@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 3,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Redesign Icons #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-17",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Test API Endpoints #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-27",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "API Response Delay Fix #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-04",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Unit Tests #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-16",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Test API Endpoints #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-01",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 35,
    "firstName": "Manish",
    "email": "test35@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 1,
      "failed": 2
    },
    "tasks": [
      {
        "title": "Update README File #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-01",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "User Feedback Testing #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-27",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Log Cleanup #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-22",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Dark Mode Design #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-02",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 36,
    "firstName": "Esha",
    "email": "test36@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 4,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Update README File #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-03",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Implement Loader #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-23",
        "category": "Testing",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Update README File #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-06",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix NavBar #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-14",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-28",
        "category": "Development",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Write Deployment Guide #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-14",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix NavBar #7",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-14",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 37,
    "firstName": "Alisha",
    "email": "test37@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Test Mobile Layout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-25",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "User Feedback Testing #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-17",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 38,
    "firstName": "Vivek",
    "email": "test38@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 1,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Log Cleanup #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-14",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-04",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Redesign Icons #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-10",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 39,
    "firstName": "Anjali",
    "email": "test39@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 1,
      "completed": 1,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Write Unit Tests #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-29",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Improve Animations #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-21",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Prepare Release Notes #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-11",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 40,
    "firstName": "Neha",
    "email": "test40@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 0,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Redesign Icons #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-09",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Prepare Release Notes #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-27",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 41,
    "firstName": "Nikhil",
    "email": "test41@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 0,
      "completed": 2,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Database Migration #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-07",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Design Login Page #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-09",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 42,
    "firstName": "Tanya",
    "email": "test42@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Create Contact Page #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-13",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Add Modal Window #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-12",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-18",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 43,
    "firstName": "Rahul",
    "email": "test43@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 1,
      "completed": 3,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Fix Mobile Layout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-17",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Design Icons #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-17",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Update README File #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-05",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Improve Animations #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-24",
        "category": "Design",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Fix API Timeout #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-08",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Dark Mode Design #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-11-22",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Update README File #7",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-01",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 44,
    "firstName": "Karan",
    "email": "test44@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 0,
      "completed": 0,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Database Migration #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-03",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix API Timeout #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-10-31",
        "category": "Documentation",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Unit Tests #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-02-14",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      }
    ]
  },
  {
    "id": 45,
    "firstName": "Yash",
    "email": "test45@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Log Cleanup #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-26",
        "category": "Analytics",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "User Feedback Testing #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-22",
        "category": "Design",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 46,
    "firstName": "Arjun",
    "email": "test46@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 1,
      "completed": 0,
      "failed": 1
    },
    "tasks": [
      {
        "title": "Design Login Page #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-07",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Build Dashboard Page #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-06-24",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": false,
        "failed": true
      },
      {
        "title": "Add Modal Window #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-22",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 47,
    "firstName": "Abhishek",
    "email": "test47@e.com",
    "password": "123",
    "taskCount": {
      "active": 1,
      "newTask": 0,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Test API Endpoints #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-04",
        "category": "Testing",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Log Cleanup #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-04",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      }
    ]
  },
  {
    "id": 48,
    "firstName": "Avinash",
    "email": "test48@e.com",
    "password": "123",
    "taskCount": {
      "active": 2,
      "newTask": 1,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Deploy to Production #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-09",
        "category": "Design",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "User Feedback Testing #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-21",
        "category": "Development",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      },
      {
        "title": "Create Contact Page #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-07-08",
        "category": "Testing",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Dark Mode Design #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-08-06",
        "category": "Analytics",
        "active": true,
        "newTask": false,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 49,
    "firstName": "Rohan",
    "email": "test49@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 5,
      "completed": 1,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Deploy to Production #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-05-19",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Team Report #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-09",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Deployment Guide #3",
        "description": "Autogenerated task for testing.",
        "date": "2025-12-20",
        "category": "Development",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Button Style #4",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-05",
        "category": "Documentation",
        "active": false,
        "newTask": false,
        "completed": true,
        "failed": false
      },
      {
        "title": "Log Cleanup #5",
        "description": "Autogenerated task for testing.",
        "date": "2025-09-26",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Write Team Report #6",
        "description": "Autogenerated task for testing.",
        "date": "2025-04-10",
        "category": "Documentation",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  },
  {
    "id": 50,
    "firstName": "Divya",
    "email": "test50@e.com",
    "password": "123",
    "taskCount": {
      "active": 0,
      "newTask": 2,
      "completed": 0,
      "failed": 0
    },
    "tasks": [
      {
        "title": "Fix Mobile Layout #1",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-08",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      },
      {
        "title": "Fix Login Bug #2",
        "description": "Autogenerated task for testing.",
        "date": "2025-01-28",
        "category": "Analytics",
        "active": false,
        "newTask": true,
        "completed": false,
        "failed": false
      }
    ]
  }
];

export default employees;


const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];
// localStorage.clear();


export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
if (!localStorage.getItem("employees")) {
  setLocalStorage();
}

